#
# broker.yml
#
# Simple yaml file for the env specific configuration of the broker connections.
# See the wiki for more information: http://code.google.com/p/activemessaging/wiki/Configuration
#
development:
    ############################
    # Stomp Adapter Properties #
    ############################
    # adapter: stomp

    ## properties below are all defaults for this adapter
    # login: ""
    # passcode: ""
    # host: localhost
    # port: 61613
    # reliable: true
    # reconnectDelay: 5
    
    # NEW! enable stomp retry logic
    #  will resend errored out messages to be retried when on_error throws ActiveMessaging::AbortMessageException
    #
    # Max number of times to retry an aborted message, for 0, will not retry (default)
    # retryMax: 0
    #
    # If error still occurs after retryMax, send message to specified dead letter queue
    # deadLetterQueue: '/queue/activemessaging/deadletter'


    ###################################
    # Websphere MQ Adapter Properties #
    ###################################
    # adapter: wmq
    # q_mgr_name: ""
    # poll_interval: .1


    ################################
    # Amazon SQS Adapter Properties #
    ################################
    adapter: asqs
    access_key_id: "04WAVZJW4HAZZQTWKCR2"
    secret_access_key: "/iEjATrlFcU9k7pyPQSWjtfI8AnylH1CXs33TrvI"
    
    ## properties below are all defaults for this adapter
    host: queue.amazonaws.com
    port: 443
    protocol: https
    reliable: true
    reconnectDelay: 5
    # aws_version: 2007-05-01 
    # 2009-02-01 
    aws_version: 2008-01-01 
    # 2007-05-01 have been deprecated
    # 2006-04-01 have been deprecated
    
    content_type: text/plain
    poll_interval: 1
    cache_queue_list: true

    ########################################
    # ReliableMessaging Adapter Properties #
    ########################################
#     adapter: reliable_msg
#     
#     ## properties below are all defaults for this adapter
#     poll_interval: 1
#     reliable: false    
#     tx_timeout: 1

test:
    adapter: reliable_msg

    ## properties below are all defaults for this adapter
    poll_interval: 1
    reliable: true  

production:
    ################################
    # Amazon SQS Adapter Properties #
    ################################
    adapter: asqs
    access_key_id: "04WAVZJW4HAZZQTWKCR2"
    secret_access_key: "/iEjATrlFcU9k7pyPQSWjtfI8AnylH1CXs33TrvI"
    
    ## properties below are all defaults for this adapter
    host: queue.amazonaws.com
    port: 443
    protocol: https
    reliable: true
    reconnectDelay: 5
    # aws_version: 2007-05-01 
    # 2009-02-01 
    aws_version: 2008-01-01 
    # 2007-05-01 have been deprecated
    # 2006-04-01 have been deprecated
    
    content_type: text/plain
    poll_interval: 1
    cache_queue_list: true

