#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

escaped_hostname = Ec2Instance.escape_primary_key(`hostname`.strip)
me = Ec2Instance.find escaped_hostname
me.aws_state = Ec2Instance::RUNNING
me.save
